# Tugas Pertemuan Kelima

## 5.16 List 2 Dimensi

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list.
Penggambarannya seperti sebuah matrik.

#### Contoh Penerapan List 2 Dimensi

In [1]:
# dengan menggunakan contoh matriks
# disini diberikan 4 buah matriks
# yang dimana 4 buah matriks ini merupakan sebuah list yang didalamnya berisi list

# masukan variabelnya, yaitu matriks
# list harus berada didalam tanda []
# karena diisni merupkan list didalam list, maka penggunaan tanda [] double 
# [ berada di atas sebelum adanya list, kemudia penutupnya berada dibawah list
# berikut contohnya 
matriks = [
    [1,5,9,10],
    [3,7,11,12],
    [5,8,10,13],
    [7,5,9,10]
]
# kemudian mari mencoba untuk print
# seperti biasa ketik "  print (variabel)   "
print (matriks)\
# hasil yang muncul adalah list yang dimasukan dalam variabel matriks

[[1, 5, 9, 10], [3, 7, 11, 12], [5, 8, 10, 13], [7, 5, 9, 10]]


In [2]:
# memanggil salah satu list dari variabel matriks
# matriks memiliki 4 buah list, dengan masing masing memiliki 4 anggotanya
# 4 buah list tersebut memiliki urutan dari 0 sampai 3
# disini mencoba untuk memanggil list urutan ke 0

# masukan variabelnya yaitu matriks dengan urutannya, urutan matriks ditandai dengan []
# contohnya seperti dibawah ini
matriks[0]
# maka outputnya adalah urutan ke 0 dari list variabel matriks

[1, 5, 9, 10]

In [3]:
# contoh 1
# memanggil salah satu anggota list dari suatu list
# urutan dari atas ke bawah disebut dengan baris
# urutan dari kiri ke kanan disebut dengan kolom

# masukan variabelnya yaitu matriks, lalu masukan salah satu baris beserta kolomnya yang ingin dipanggil
# disini semua urutan dimulai dari 0
# saya memasukan baris 0 kolom 3
# jangan lupa kolom dan baris diberi tanda []
matriks [1][2]
# maka outputnya adalah 11, bisa di cek sendiri secara manual.

11

In [4]:
# contoh 2
# memanggil salah satu anggota list dari suatu list
# urutan dari atas ke bawah disebut dengan baris
# urutan dari kiri ke kanan disebut dengan kolom

# masukan variabelnya yaitu matriks, lalu masukan salah satu baris beserta kolomnya yang ingin dipanggil
# disini semua urutan dimulai dari 0
# saya memasukan baris 3 kolom 1
# jangan lupa kolom dan baris diberi tanda []
matriks[3][1]
# maka outputnya adalah 5, bisa di cek sendiri secara manual.

5

In [5]:
# mengganti salah satu anggota list dari suatu list
# disini saya ingin mengganti baris 2 kolom 3, menjadi 50

# masukan variabelnya beserta bagian kolom dan baris yang mana yang ingin diganti
# lalu masukan angka terbarunya
# kolom dan baris diberi tanda [], lalu diberi = masukan angka terbaru
# dengan contoh seperti dibawah ini
matriks[2][3] = 50

# mari kita cek, apakah baris 2 kolom 3 sudah terganti menjadi 50 atau belum
# mencoba untuk memanggil baris 2 kolom 3
# ketik print (variabel[baris][kolom])
# dengan contoh dibawah ini
print (matriks[2][3])
# outputnya adalah 50
# berarti baris 2 kolom 3 sudah terganti
# sebelum dirubah baris 2 kolom 3 adalah 13 

50


In [6]:
# mencoba memanggil matriks
# mengecek apakah yang akan muncul adalah matriks yang sebelum dirubah atau sudah dirubah
# ketik matriks
matriks
# hasil yang muncul dalah yang sudah diperbarui

[[1, 5, 9, 10], [3, 7, 11, 12], [5, 8, 10, 50], [7, 5, 9, 10]]

#### Cara memanggil anggota dari list 2 dimensi

In [7]:
# memanggil anggota dari list di dalam list dengan menggunakan for
# baris in matriks maksudnya baris berada didalam matriks
# akhir dari for diberi tanda :
for baris in matriks:
    print(baris)
# memanggil baris dari matriks
# maka baris yang muncul adalah dari baris 0 sampai baris 3

# selanjutnya kolom in baris
# akhir dari for diberi tanda :
    for kolom in baris:
        print (kolom)
# memanggil kolom dari matriks, berdasarkan urutan barisnya

# sehingga outputnya adalah memnuculkan baris dari 0 sampai baris 3
# dengan menampilkan juga anggotanya, atau disebut kolom dari barisnya
# dengan baris horizontal
# kolom vertikal

[1, 5, 9, 10]
1
5
9
10
[3, 7, 11, 12]
3
7
11
12
[5, 8, 10, 50]
5
8
10
50
[7, 5, 9, 10]
7
5
9
10


## 5.17 Tuples

Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita
memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan
jika datanya masih ingin dimanipulasi kedepannya, gunakan list.

#### Contoh penerapan tuples pada Python

In [8]:
# perbedaan secara kode antara tuples dan list adalah penggunaan tanda kurungnya
# list menggunakan tanda kurung []
# tuples menggunakan tanda kurung ()

# masukan variabelnya beserta dengan isinya
# isinya diberi tanda ()
# disini saya menggunakan contoh bilangan prima
bilangan_prima = (2,3,7,11,13,17)

# lalu kita coba untuk memanggil salah satu anggotanya
# ketik print(variabel[urutan yang ingin dipanggil])
# dengan contoh seperti dibawah ini
print(bilangan_prima[5])
# sama dengan seblumnya urutan nya berawal dari 0

17


In [9]:
# memanggil anggotanya dengan menggunakan interval

# ketik print(variabel[intervalnya])
# disini saya menggunakan 0:4
# yang artinya urutan 0<= bilangan prima < 4
# diperhatikan kembali bahwa urutan ke 4 tidak dipanggil
print (bilangan_prima[0:4])

(2, 3, 7, 11)


In [10]:
# memanggil anggotanya dalam bentuk barisan dengan menggunakan for
# akhir dari for diberi tanda :
# disini saya menggunakan 0:4
# yang artinya urutan 0<= bilangan prima < 4
for isi in bilangan_prima[0:4]:
# yang dimana isi nya itu adalah anggota yang dipanggil dalam bentuk interval
    print (isi)
# hasil yang muncul adalah angka yang sama dengan sebelumnya, namun dalam bentuk yang berbeda

2
3
7
11


In [11]:
# dalam menggunakan tuples, isinya tidak dapat dirubah
# disini akan membuktikan bahwa tuples tidak dapat dirubah isinya

# masukan variabel[urutan yang ingin diganti] = masukan angka yang baru
bilangan_prima[1] = 8
# maka hasilnya adalah eror
# sebab dalam tuples, isi tidak dapat diganti

TypeError: 'tuple' object does not support item assignment

In [12]:
# dalam menggunakan tuples, tidak bisa menambahkan anggota lagi
# disini akan membuktikan bahwa tuples tidak dapat menambahkan anggota

# dalam menambahkan anggota menggunakan append
# variabel.append(angka yang ingin ditambahkan)
bilangan_prima.append(5)
# hasil yang muncul yaitu eror, karena dalam tuples idak bisa menambahkan anggota baru

AttributeError: 'tuple' object has no attribute 'append'

In [13]:
# selain menambahkan, mengurangi/menghapus didalam tuples juga tidak bisa
# disini akan membuktikan bahwa didalam tuples tidak bisa mengurangi/menghapus anggotanya

# remove digunakn untuk menghapus anggotanya
#variabel.remove(angka yang ingin dihapus)
angka.remove(2)
# hasil yang muncul adalah eror, sesuai dengan pernyataan diatas
# bahwa dalam tuples tidak bisa menghapus anggota didalam variabelnya

NameError: name 'angka' is not defined

In [14]:
# menghitung banyaknya jumlah anggota yang sama 

# count digunakan untuk menghitung
# variabel.count(angka yang ingin dihitung banyaknya)
bilangan_prima.count(7)
# jumlah dari bilangan 7 hanya ada satu

1

In [15]:
# menghitung banyaknya jumlah anggota yang sama 

# count digunakan untuk menghitung
# variabel.count(angka yang ingin dihitung banyaknya)
bilangan_prima.count(5)
# 5 tidak termasuk anggota dari variabel bilangan_prima
# sehingga hasil yang muncul adalh 0

0

In [16]:
# mencari tau urutan keberapa angka yang diinginkan

# untuk mencari tau urutan dari angka yang dimasukan, kita menggunakan index
# variabel.index(angka yang ingin dicari tau)
bilangan_prima.index(7)
# dilihat dari anggota variabel bilangan_prima, bahwa 7 berada di urutan ke 2
# urutan dimulai dari 0

2

In [17]:
# mencoba mencari index yang bukan menajdi anggota dari variabel bilangan_prima
bilangan_prima.index(1)
# hasilnya yang muncul adalah eror, karena 1 bukan anggota dari variabel bilangan_prima

ValueError: tuple.index(x): x not in tuple

## 5.18 Dictionaries

Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data
seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan
data yang bersumber dari orang tersebut.

#### Contoh Dictionaries

In [18]:
# menggunakan Dictionaries dengan data mahasiswa

# masukan variavelnya 
# didalam variabel berisi data seperti nama, umur, dan lainnya
# data tersebut dimasukan kedalam tanda {}
# seperti contoh dibawah ini
data_mahasiswa = {
    "nama" : "Nyoman Paul",
    "umur" : 19, 
    "apakah_prodi_matematika" : False
}

# kemudian coba untuk memanggil nama dari varaibel data_mahasiswa
# print(variabel["data yang ingin dipanggil"])
# jangan lupa untuk memberi tanda [] dan "" atau ''
print (data_mahasiswa["nama"])
# hasil yang muncul adalah data nama yaitu Nyoman Paul

Nyoman Paul


In [19]:
# penggunaan huruf besar atau kecil itu berpengaruh terhadap kodenya
# misal kita akan memanggil Nama bukan nama dari data tersebut 

# print (variabel['data yang ingin dipanggil'])
# jangan lupa untuk memberi tanda [] dan "" atau ''
print (data_mahasiswa['Nama'])
# maka yang terjadi adalah eror, karena yang data yang dimasukan dalam variabel nama bukan Nama

KeyError: 'Nama'

In [20]:
# selain cara diatas untuk memanggil suatu data
# terdapat cara lain, yaitu dengan menggunakan get

# print(variabel.get("data yang ingin dipanggil"))
# perbedaan yang terlihat juga dengan penggunaan tanda kurung yang berbeda
print (data_mahasiswa.get("nama"))

Nyoman Paul


In [21]:
# memanggil data dengan menggunakan get
# untuk contoh ini saya, saya memberikan contoh yang salah
# penggunaan huruf besar atau kecil itu berpengaruh terhadap kodenya
# misal kita akan memanggil Nama bukan nama dari data tersebut 

# print(variabel.get("data yang ingin dipanggil"))
print (data_mahasiswa.get("Nama"))
# untuk contoh ini hasil yang kleuar tidak eror, melainkan none
# yang dimana data yang dipanggil adalah Nama, sedangkan dalam variabel data_mahasiswa tidak ada data berupa Nama

None


In [22]:
# mencoba memanggil data yang tidak dimasukan kedalam variabel
# disini akan mencoba memanggil data tanggal lahir
print (data_mahasiswa.get("tanggal lahir"))
# maka hasil yang muncul adalah none, karena tidak ada data berupa tanggal lahir didalam variabel data_mahasiswa
# karena tidak ada data tanggal lahir, maka hasil yang muncul adalah none

None


In [23]:
# memanggil data baru dengan langsung menambahkan datanya, dengan menggunakan get
# menambahkan data tanggal lahir pada variabel data mahasiswa

# print(variabael.get("tanggal_lahir", "masukan tanggal lahir"))
# jangan lupa tanda '' atau ""
print(data_mahasiswa.get("tanggal_lahir", "16 Juni 2001"))
# untuk contoh ini memunculkan tanggal lahr dan juga menambahkannya
# karena yang dipanggil hanya tanggal lahir, maka output yang dihasilkan berupa tanggal lahir saja

16 Juni 2001


In [24]:
# memncoba memanggil data mahasiswa
# membuktikan hasil yang muncul sudah sama dengan tanggal lahirnya atau belum

# print(variabel)
print (data_mahasiswa)
# ternyata hasil yang muncul tidak dengan tanggal lahir
# sesuai dengan data yang dimasukan pertama kali ke variabel data_mahasiswa
# ini dikarenakan apabila menggunakan get hasilnya tidak menetap

{'nama': 'Nyoman Paul', 'umur': 19, 'apakah_prodi_matematika': False}


In [25]:
# memastikan apakah data tanggal lahir tidak masuk pada data variabel data_mahasiswa

# print(variabel["tanggal-lahir"])
print(data_mahasiswa["tanggal_lahir"])
# ternyata hasil yang muncul adalah eror
# karena tanggal_lahir tidak ditemukan pada variabel data_mahasiswa

KeyError: 'tanggal_lahir'

In [26]:
# CONTOH YANG BENAR APABILA MENAMBAHKAN DATA PADA SUATU VARIABEL

# variabel["data yang ingin ditambahkan"] = "isi datanya"
data_mahasiswa["HP"] = '08123456789'

In [27]:
# memastikan apakah HP sudah terdaftar di variabel data_mahasiswa

# print (variabel["data yang ingin dipanggil"])
print (data_mahasiswa["HP"])
# hasil yang muncul adalah no HP yang sudah dimasukan sebelumnya
# sehingga terbukti bahwa HP merupakan data dari variabel data_mahasiswa

08123456789


In [28]:
# membuktikan hasil yang muncul apabila memanggil variabel data_mahasiswa
# apakah data HP akan muncul atau tidak

# print (variabel yang ingin dipanggil)
print (data_mahasiswa)1
# terbukti bahwa data HP termasuk dalam variabel data_mahasiswa

SyntaxError: invalid syntax (3080644831.py, line 5)

## 5.19 Fungsi dalam Python

Sampai sejauh ini tanpa disadari kita telah menerapkan beberapa jenis fungsi
pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi
dibentuk untuk menghidari pengulangan pembuatan program secara manual
dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang
kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat,
setiap fungsi tersebut dibutuhkan tinggal kita panggil.

#### Contoh fungsi dalam Python

In [29]:
# dalam contoh ini, akan membuat fungsi dalam Python
# disini akan menggunakan def
# contoh ini berupa nama lengkap, yang berisi nama depan dan nama belakang

# def variabel nama lengkap(nama depan,nama belakang) :
# jangan lupa untuk memberi tanda :
def full_name(first_name,last_name) :

# dengan memunculkan hasil gabungan dari nama depan dan nama belakang atau disebut nama lengkap
# untuk bagian ini akan menjorok sedikit kedalam
# print (f"kata yang ingin ditampilkan {variabel 1} {variabel 2})
# f digunakan untuk menggabungkan variabelnya
    print (f"Nama lengkapnya adalah {first_name} {last_name}")
# ketika di run, kode ini memang tidak menampilkan output
# karena hanya berupa fungsi

In [31]:
# Disini akan memunculkan hasil dari fungsi diatas 
# dengan konsepnya menggunakan input
# memasukan nama depan dan nama belakang

# variabel 1 = input ("kata yang ingin ditampilkan")
# selalu ingat menggunakan tanda ""
first_name = input("Nama depan anda adalah ")

# variabel 2 = input ("kata yang ingin ditampilkan")
# selalu ingat menggunakan tanda ""
last_name = input("Nama belakang anda adalah ")

# untuk menampilkan nama lengkapnya tidak menggunakan input lagi
# menggunakan fungsi diatas yang sudah dibuat sebelumnya
full_name(first_name,last_name)

Nama depan anda adalah intan
Nama belakang anda adalah pratiwi
Nama lengkapnya adalah intan pratiwi


### 5.19.1 Tugas Fungsi pada Python

Ada dua jenis tugas fungsi pada Python yaitu:
1. Menjalankan perintah.
2. Menampilkan hasil perhitungan.

#### Contoh Tugas Fungsi pada Python 

In [32]:
# kata kucinya terdapat di def
# dimana def menjadi pertanda bahwa kode berupa fungsi

# def nama fungsi(parameter): 
    # disini berisi statements
def luas_segitiga(alas,tinggi):
# luas dari segitiga adalah 1/2 x alas x tinggi
# dimana 1/2 bisa diganti menajdi 0.5
# tanda x menggunakan simbol *
    luas = 0.5 * alas * tinggi
# selanjutnya adalah dengan menampilakn luas nya
    print(luas)
# dimana ini sebuah fungsi, tidak menampilkan output

In [33]:
# Fungsi mengembalikan nilai (return)
# fungsi yang mengembalikan nilai adalah sebuah fungsi yang jika kita panggil, 
# dia akan memberikan nilai kita sebuah nilai yang bisa kita olah lebih lanjut
def luas_segitiga_baru(alas,tinggi) :
    luas = 0.5 * alas * tinggi
# return berfungsi untuk mengemblikan nilai
    return luas

In [34]:
# memanggil luas segitiga dengan alas = 6 dan tinggi = 5
# nama fungsi(parameternya)
luas_segitiga(6,5)
# maka output yang muncul adalah hasil dari luas segitiga dengan alas = 6 dan tinggi = 5

15.0


In [35]:
# disini mencoba untuk menggunakan fungsi mengembalikan nilai atau return
# nama fungsi yang return(parameter)
luas_segitiga_baru(6,5)
# maka output yang muncul akan sama dengan fungsi sebelumnya atau dengan kode diatasnya

15.0

In [36]:
# disini akan memberikan variabel pada luas segitiga yaitu a
# variabel = nama fungsi (parameter)
a = luas_segitiga(6,5)
# kemudia kita coba untuk print
print (a)
# maka hasil yang muncul adalah tetap sama yaitu 15, tetapi dengan tambahan none

15.0
None


In [37]:
# pada percobaan fungsi return
# disini akan memberikan variabel pada luas segitiga baru yaitu b
# variabel = nama fungsi return (parameter)
b = luas_segitiga_baru(6,5)
# kemudian kita coba print
print (b)
# maka outputnya sama dengan sebelumnya yaitu 15
# tetapi bedanya disini tidak menampilkan none

15.0


##  5.20 Numpy

Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan
dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi.

In [38]:
# Hal pertama yang perlu dilakukan adalah memanggil Library Numpy sebagai berikut:
import pandas as pd

In [39]:
import numpy

### 5.20.1 Perintah Dasar pada Numpy

Berikut akan dipaparkan mengenai beberapa perintah dalam Numpy diantaranya
memanggil Numpy, mengetahui dimensi dan ukuran variabel

In [40]:
# contoh 1
# masukan nama variabel yang diinginkan
# gunakan fungsi numpy yang sudah diinisiasikan sebelumnya yaitu numpy
# kemudian diikuti fungsi array 
# diikuti kurung dua () yang diisi dengan nilai array dalam kurung siku []
a = numpy.array([0,1,2,3,4])
print (a)
# pada a, dimensi nilai yang diisikan hanya dalam satu baris
# perlu diingat nilai array hanya berisi satu tipe data yang sama

[0 1 2 3 4]


In [41]:
# contoh 2
# penulisannya masih sama dengan contoh 1
# yang membedakan adalah pada isi array yang berisi dua baris data dengan jumlah yang sana

# masukan nama variabel yang diinginkan
# gunakan fungsi numpy yang sudah diinisiasikan sebelumnya yaitu numpy
# kemudian diikuti fungsi array 
# diikuti kurung dua () yang diisi dengan nilai array dalam kurung siku []
b = numpy.array([[5,6,7,8],[9,8,7,6]])
print(b)
# pada b, dimensi nilai yang diisikan hanya dalam dua baris
# perlu diingat nilai array hanya berisi satu tipe data yang sama

[[5 6 7 8]
 [9 8 7 6]]


In [42]:
# contoh 3
# penulisannya masih sama dengan contoh sebelumnya
# yang membedakan adalah pada isi array yang berisi 3 dimensi dengan dua baris data dan jumlah yang sana

# masukan nama variabel yang diinginkan
# gunakan fungsi numpy yang sudah diinisiasikan sebelumnya yaitu numpy
# kemudian diikuti fungsi array 
# diikuti kurung dua () yang diisi dengan nilai array dalam kurung siku []
c = numpy.array([[[0,1,2,3],[4,5,6,7]],[[8,9,8,7],[6,5,4,3]],[[1,2,3,4],[5,6,7,8]]])
print(c)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


.ndim berfungsi untuk menghitung dimensi array

In [43]:
# menghitung dimensi array dari contoh 1
a.ndim
# karena hanya terdiri dari 1 baris

1

In [44]:
# menghitung dimensi array dari contoh 2
b.ndim
# karena pada contoh 2, terdiri dari 2 baris

2

In [45]:
# menghitung dimensi array dari contoh 3
c.ndim
# pada contoh 3 terdiri dari 3 baris, yang dimana setiap baris memiliki baris lagi sebnyak 2 baris

3

.shape berfungsi menghitung isi dari array

In [46]:
# menghitung isi array dari contoh 1
a.shape
# pada contoh 1 banyaknya elemen adalah 5, dengan terdiri dari 1 baris
# kerena hanya satu baris, maka yang muncul hanya (5,)

(5,)

In [47]:
# menghitung isi array dari contoh 1
b.shape
# banyaknya dimensi adalah 2 baris
# banyaknya elemen disetiap dimensi adalah 4 

(2, 4)

In [48]:
# menghitung isi array dari contoh 3
c.shape
# pada contoh 3 banyaknya dimensi adalah 3 
# pada setiap dimensi terdiri dari 2 baris 
# banyaknya elemen di setiap baris berjumlah 4

(3, 2, 4)

### 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [49]:
# masukan variabel
# gunakan fungsi numpy yang sudah diinisiasikan sebelumnya yaitu numpy
# kemudian diikuti fungsi array 
# diikuti kurung dua () yang diisi dengan nilai array dalam kurung siku []
x = numpy.array([[10,11,12,13],[15,16,17,18],[20,21,22,23]])
print (x)

[[10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]


In [50]:
# memanggil salah satu anggota
# masukan variabel yang diikuti baris dan kolomx yang berada didalam kurung []
x[2,0]
# pada contoh diatas, urutan baris dan kolom dimulai dari 0
# kolom yang bentuknya horizontal (kiri-kanan)
# dan baris bentuknya vertikal (atas-bawah)

20

In [51]:
# memanggil baris
# masukan variabelnya [baris, kolom]
# urutan baris dan kolom dimulai dari 0
x[1,:]
# kode diatas itu memanggil baris urutan 1 beserta semua elemennya
# tanda : maksudnya memanggil semua di barisan 1 secara horizontal

array([15, 16, 17, 18])

In [52]:
# memanggil kolom
# masukan variabelnya [baris, kolom]
# urutan baris dan kolom dimulai dari 0
x[:,0]
# kode diatas memanggil semua barisan di kolom 0
# semua elemen di kolom 0 dipanggil

array([10, 15, 20])

In [53]:
# memanggil anggota tertentu
# masukan variabelnya [baris, interval kolom]
# urutan baris dan kolom dimulai dari 0
x[2,1:3]
# kode diatas memanggil anggota di barisan ke 2, dengan batas kolom dari urutan 1 sampai urutan 2

array([21, 22])

In [54]:
# memanggil anggota tertentu
# masukan variabelnya [baris, interval kolom]
# urutan baris dan kolom dimulai dari 0
x[0,0:3:2]
# kode diatas memanggil anggota di barisan ke 0
# dengan batasan dari kolom ke 0 sampai 2, dengan 2 loncatan

array([10, 12])

In [55]:
# merubah atau mengganti salah satu anggota
# masukan variabelnya [baris, kolom] = angka yang ingin di isi
# urutan baris dan kolom dimulai dari 0
x[0,2] = 200
# kemudian print variabel, untuk mencetak hasilnya
print(x)
# sehingga hasil yang muncul adalah barisan ke 0, kolom ke 2 yang sudah diperbarui

[[ 10  11 200  13]
 [ 15  16  17  18]
 [ 20  21  22  23]]


### 5.20.3 Matrix pada Numpy

Numpy dapat digunakan untuk membuat berbagai jenis matrix

In [56]:
import numpy

In [57]:
numpy.ones((2,3))
numpy.zeros((3,2))
numpy.identity(4)
numpy.ones((2,3,4))
numpy.full((3,2),9)
numpy.random.rand(4,3)
numpy.random.randint(1,10,size=(3,4))

array([[4, 3, 5, 5],
       [9, 9, 4, 9],
       [8, 7, 7, 7]])

### Copy pada Numpy

Sering sekali kita menduplikat suatu variabel dengan maksud untuk mempercepat pekerjaan kita. Akan tetapi sering tanpa disadari ikatan persamaan
dalam Numpy sedemikian eratnya sehingga saat anggota variabel baru dirubah,
dampaknya juga akan merubah variabel asal. Untuk menghindari perubahan
variabel awal yang tidak dikehendaki maka diperlukan perintah copy

In [58]:
# memasukan variabel p
# gunakan fungsi numpy yang sudah diinisiasikan sebelumnya yaitu numpy
# kemudian diikuti fungsi array 
# diikuti kurung dua () yang diisi dengan nilai array dalam kurung siku []
p = numpy.array([7,8,9,10,11])
print (p)

[ 7  8  9 10 11]


In [59]:
# contoh 1
# disini copy numpy menggunakan persamaan
# sebagai contoh, disini saya menggunakan q=p

# masukan variabel baru, diikuti dengan = variabel yang ingin di copy
q = p
# karena ingin copy p, maka yang di print adalah q nya
print (q)
# sehingga hasil yang muncul adalah sama dengan p

[ 7  8  9 10 11]


In [60]:
# ketika ingin mengganti salah satu anggotanya di q
# masukan variabelnya diikuti dengan urutan yang ingin diganti, dengan tanda []
# masukan angka baru
q[1] = 15
print (q)
# sehingga hasil yang muncul adalah q dengan yang sudah diperbarui

[ 7 15  9 10 11]


In [61]:
# sekarang kita coba untuk panggil p
print (p)
# ternyata hasil yang muncul adalah mengikuti q yang sudah diperbaarui
# hal itu dikarenakan, berdasarkan variabel yang sudah dimasukan 
# bahwa p=q, jadi ketika q berubah maka p juga ikut berubah

[ 7 15  9 10 11]


In [62]:
# contoh 2
# masukan variabel baru, yaitu r
# gunakan fungsi numpy yang sudah diinisiasikan sebelumnya yaitu numpy
# kemudian diikuti fungsi array 
# diikuti kurung dua () yang diisi dengan nilai array dalam kurung siku []
r = numpy.array([7,8,9,10,11])
print(r)

[ 7  8  9 10 11]


In [63]:
# disini akan membuat variabel baru dengan copy dari variabel r
# dengan menggunakan .copy yang diikuti dengan tanda ()
# berbeda dengan seblumnya
s = r.copy()
# kemudian kita coba untuk panggil s
print (s)
# maka hasil yang muncul adalah isi yang sama dengan r

[ 7  8  9 10 11]


In [64]:
# disini akan mengganti salah satu anggota di s
# masukan variabelnya diikuti dengan urutan yang ingin diganti, dengan tanda []
# masukan angka baru
# ingat, urutan berawal dari 0
s[1] = 20
print(s)
# hasil yang muncul adalah isi dari s yang sudah diperbarui

[ 7 20  9 10 11]


In [65]:
# apakah contoh 2 sama dengan contoh 1?
# yang ketika diganti maka variabel sebelumnya juga ikut berubah ?
# disini akan membuktikan hal tersebut
# mari coba untuk panggil r, variabel yang dicopy dengan s
print (r)
# terlihat hasil yang muncul tidak ada perubahan, r tidak mengikuti perubahan dari s

## jadi itu yang membedakan dari contoh 1 dan contoh 2

[ 7  8  9 10 11]


### 5.20.5 Operasi Matematika pada Numpy 

In [66]:
import numpy

In [67]:
# memasukan variabel p
# gunakan fungsi numpy yang sudah diinisiasikan sebelumnya yaitu numpy
# kemudian diikuti fungsi array 
# diikuti kurung dua () yang diisi dengan nilai array dalam kurung siku []
p = numpy.array([7,8,9,10,11])
p+1
# hasil yang muncul adalah penjumlahan +1 di setiap anggotanya

array([ 8,  9, 10, 11, 12])

In [68]:
# operasi pengurangan
# variabel dikurang dengan jumlah yang diinginkan
p-3
# hasil yang muncul adalah pengurangan -3 di setiap anggota p

array([4, 5, 6, 7, 8])

In [69]:
# operasi perkalian
# simbol dalam perkalian adalah *
# variabel*angka yang ingin dikalikan
p*2
# hasil yang muncul adalah perkalian, dikali 3 di setiap anggota p

array([14, 16, 18, 20, 22])

In [70]:
# operasi pembagian
# yang digunakan dalam pembagian adalah /
# variabel/angka yang ingin dibagi
p/2
# hasil yang muncul adalah pembagian, dibagi 2 di setiap anggota p

array([3.5, 4. , 4.5, 5. , 5.5])

In [71]:
# operasi pemangkatan
# simbol yang digunakan dalam pemangkatan adalah **
p**2
# hasil yang muncul adalah pemangkatan, dipangkat 2 di setiap anggota p

array([ 49,  64,  81, 100, 121], dtype=int32)

In [72]:
# dengan memasukan variabel baru lagi
q = numpy.array([5,6,7,8,9])
print (q)

[5 6 7 8 9]


In [73]:
# penjumlahan diantara 2 variabel
p+q
# hasil yang muncul adalah operasi penjumlahan diantara sesama anggota p dan q, dengan berdasarkan urutannya

array([12, 14, 16, 18, 20])

In [74]:
# pengurangan diantara 2 variabel
p-q
# hasil yang muncul adalah operasi pengurangan diantara sesama anggota p dan q, dengan berdasarkan urutannya

array([2, 2, 2, 2, 2])

In [75]:
# perkalian diantara 2 variabel
p*q
# hasil yang muncul adalah operasi perkalian diantara sesama anggota p dan q, dengan berdasarkan urutannya

array([35, 48, 63, 80, 99])

In [76]:
# pembagian diantara 2 variabel
p/q
# hasil yang muncul adalah operasi pembagian diantara sesama anggota p dan q, dengan berdasarkan urutannya

array([1.4       , 1.33333333, 1.28571429, 1.25      , 1.22222222])

In [77]:
# pemangkatan sesama 2 variabel
p**q
# hasil yang muncul adalah operasi pemangkatan sesama anggota p dan q, dengan berdasarkan urutannya

array([      16807,      262144,     4782969,   100000000, -1937019605],
      dtype=int32)

In [78]:
# mencari nilai cos di setiap anggota p
# gunakan fungsi numpy diikuti dengan .cos(variabel)
numpy.cos(p)
# maka hasil yang muncul adalah nilai cos di setiap anggota p

array([ 0.75390225, -0.14550003, -0.91113026, -0.83907153,  0.0044257 ])

In [79]:
# mencari nilai sin di setiap anggota p
# gunakan fungsi numpy diikuti dengan .sin(variabel)
numpy.sin(p)
# maka hasil yang muncul adalah nilai sin di setiap anggota p

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021])

In [80]:
# mencari nilai tan di setiap anggota p
# gunakan fungsi numpy diikuti dengan .tan(variabel)
numpy.tan(p)
# maka hasil yang muncul adalah nilai tan di setiap anggota p

array([   0.87144798,   -6.79971146,   -0.45231566,    0.64836083,
       -225.95084645])

In [81]:
# sinh merupakan fungsi hiperbolik
numpy.sinh(p)

array([  548.31612327,  1490.47882579,  4051.54190208, 11013.2328747 ,
       29937.07084925])

### 5.20.6 Perkalian Matrik pada Numpy

Dapat diamati bahwa operasi matematika pada suatu matrik dengan Numpy
akan mengoperaikan elemen yang baris dan kolomnya sama. Tentunya hal ini
akan memberikan hasil berbeda jika yang kita kehendaki adalah perkalian dua
matrik. Perkalian matrik pada Numpy dapat menggunakan perintah matmul.
Perlu dijadikan perhatian tentang ukuran matrik yang akan dikalikan harus
sesuai dengan persyaratan. Misalnya matrik ukuran (2x3) dapat dikalikan dengan matrik ukuran (3x4).

In [82]:
# masukan data 
# masukan variabel baru dengan menggunakan fungsi numpy.array diikuti dengan matriks dengan []
# disini memasukan dua matriks 
w = numpy.array([[20,21,22,23],[30,31,32,33]])
# mari kita panggil w nya
print (w)
# maka hasil yang keluar adalah matriks dari variabel w

[[20 21 22 23]
 [30 31 32 33]]


In [83]:
# masukan data yang kedua
# masukan variabel baru dengan menggunakan fungsi numpy.array diikuti dengan matriks dengan []
# disini memasukan dua matriks 
x = numpy.array([[1,2,3,4],[5,6,7,8]])
print (x)
# maka hasil yang keluar adalah matriks dari variabel x

[[1 2 3 4]
 [5 6 7 8]]


In [84]:
# perkalian antara 2 matriks pada numpy

# masukan variabel = variabel 1*variabel 2
perkalian = w*x
print (perkalian)
# maka hasil yang keluar adalah perkalian dari 2 matriks, dengan dikali sesama urutannya

[[ 20  42  66  92]
 [150 186 224 264]]


In [85]:
# mencoba perkalian matriks menggunakan matmul
# masukan variabel, gunakan fungsi numpy, dengan menggunakan perintah matmul(masukan variabel1,variabel2)
z = numpy.matmul(w,x)
print(z)
# outputnya eror, karena perintah matmul akan jalan ketika sesuai persyaratan saja 
# Misalnya matriks ukuran (2x3) dapat dikalikan dengan matriks ukuran (3x4).

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [86]:
# memasukan variabel baru 
# matriks ukuran 2 x 4
v = numpy.array([[10,11],[12,23],[15,16],[17,18]])
print (v)

[[10 11]
 [12 23]
 [15 16]
 [17 18]]


In [87]:
# perkalian matriks menggunakan perintah matmul
# masukan variabel, gunakan fungsi numpy, dengan perintan matmul(variabel 1,variabel2)
q = numpy.matmul(w,v)
print (q)
# pada contoh ini perintah matmul berjalan
# karena memenuhi persyaratan, yaitu 2 matriks yang beda ukuran

[[1173 1469]
 [1713 2149]]


In [88]:
# perkalian matriks yang berbeda ukuran 
# disini akan mencoba mengalikan 2 matriks yang berbeda ukuran dengan menggunakan operasi matematika
perkalian = w*v
# ternyata hasilnya eror, hal ini dikarenakan 2 matriks yang dikalikan berbeda ukuran


### dapat disimpulkan pada perkalian matriks, menggunakan operasi matematika pada umumnya berlaku saat sesama ukuran matriks.
### matmul digunakan apabila kedua matriks berbeda ukuran

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

### 5.20.7 min, max, dan sum pada Numpy

Perintah min, max dan sum cukup sering digunakan untuk mengetahui nilai
minimum, maksimum dan penjumlahan.

In [89]:
# mendeklarasikan suatu data 

# masukan variabel, gunakan fungsi numpy.array masukan dimensi beserta anggotanya 
g = numpy.array ([[10,11,12,13],[20,21,22,23],[30,31,32,33]])
print (g)

[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [90]:
# mencari nilai min

# masukan variabel, gunakan fungsi numpy dengan perintan min(variabel)
min = numpy.min(g)
print (min)
# sesuai dengan data di g, bahwa nilai terkecil jatuh kepada 10

10


In [91]:
# axis adalah salah satu undur dari array
# axis pada array menjelaskan urutan pengindeksan dalam array
# axis 0 artinya satu dimensi

# masukan variabel baru, gunakan fungsi numpy dengan perintah min(variabel yang ingin dcari, axis=axis yang dimau)
h = numpy.min (g,axis=0)
print(h)
# maksud dari (g,axis=0) adalah di variabel g dengan anggota anggota dari satu dimensi

[10 11 12 13]


In [92]:
# axis adalah salah satu undur dari array
# axis pada array menjelaskan urutan pengindeksan dalam array
# axis 1 artinya dua dimensi

# masukan variabel baru, gunakan fungsi numpy dengan perintah min(variabel yang ingin dcari, axis=axis yang dimau)
i = numpy.min(g,axis=1)
print(i)
# maksud dari (g,axis=1) adalah di variabel g dengan anggota anggota dari dua dimensi

[10 20 30]


In [93]:
# mencari nilai max

# msukan variabel, gunakan fungsi numpy dengan perintah max(variabel yang ingin dicari nilainya)
max = numpy.max(g)
print (max)
# sesuai dengan data di g, bahwa nilai terbesar jatuh kepada 33

33


In [94]:
# axis adalah salah satu undur dari array
# axis pada array menjelaskan urutan pengindeksan dalam array
# axis 0 artinya satu dimensi
j = numpy.max(g,axis=0)
print(j)
# karena disini terdapat perintah max, maka di variabel g dengan nilai yang paling besar dan merupakan anggota dari satu dimensi

[30 31 32 33]


In [95]:
# axis adalah salah satu undur dari array
# axis pada array menjelaskan urutan pengindeksan dalam array
# axis 1 artinya dua dimensi
k = numpy.max(g,axis=1)
print(k)
# karena terdapat perintah max, maka di variabel g dengan nilai paling besar atau berada di paling kanan
# anggota anggota dari dua dimensi

[13 23 33]


In [96]:
# menghitung jumlah dengan menggunakan sum
# masukan variabel baru, gunakan fungsi numpy dengan perintah sum(masukan variabel yang ingin dijumlahkan datanya)
sum = numpy.sum(g)
print(sum)
# maka hasilnya adalah jumlah dari data di g

258


In [97]:
# menghitung jumlah dari suatu dimensi
# axis = 0, artinya satu dimensi

# masukan variabel baru, gunakan fungsi numpy dengan perintah sum(masukan variabel yang ingin datanya diambil, dimensinya)
l = numpy.sum(g,axis=0)
print(l)
# maka hasil yang muncul adalah jumlah dari satu dimensi

[60 63 66 69]


In [98]:
# menghitung jumlah dari suatu dimensi
# axis = 1, artinya dua dimensi

# masukan variabel baru, gunakan fungsi numpy dengan perintah sum(masukan variabel yang ingin datanya diambil, dimensinya)
m = numpy.sum(g,axis=1)
print (m)
# maka hasil yang muncul adalah jumlah dari dua dimensi



## dari banyaknya contoh dapat disimpulkan bahwa axis=0 adalah baris

[ 46  86 126]
